"use client";

import { useEffect, useMemo, useState } from "react";

export default function MyDonationTable({ kind = "monthly" }) {
  const [rows, setRows] = useState([]); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { setLoading(true); fetch(`/api/backend/my-account/donations/${kind === "sponsor" ? "sponsors" : "monthly"}`, { credentials: "include" }).then(async (r) => { const json = await r.json(); if (!r.ok) throw new Error(json?.message || "Unable to load donations."); setRows(json?.data ?? json ?? []); }).catch((reason) => setError(reason.message)).finally(() => setLoading(false)); }, [kind]);
  const filtered = useMemo(() => { const q=query.toLowerCase().trim(); return rows.filter((r) => !q || [r.donationNo, r.donorName, r.sponsor?.name, r.paymentMethod?.labelKm, r.paymentMethod?.labelEn, r.activity?.titleKm].some((v) => String(v || "").toLowerCase().includes(q))); }, [query, rows]);
  if (loading) return <div className="rounded-lg border bg-white p-6">Loading donations…</div>;
  return <div className="space-y-3">{error && <div className="rounded bg-red-50 p-3 text-red-700">{error}</div>}<input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search donations" className="h-10 w-full max-w-sm rounded-lg border px-3" /><div className="overflow-x-auto rounded-lg border"><table className="w-full min-w-[700px] bg-white text-sm"><thead className="bg-gray-50 text-left"><tr><th className="p-3">Number</th><th className="p-3">Donor/activity</th><th className="p-3">Period/date</th><th className="p-3">KHR</th><th className="p-3">USD</th><th className="p-3">Payment</th><th className="p-3">Recorded by</th></tr></thead><tbody>{filtered.length === 0 ? <tr><td colSpan="7" className="p-8 text-center">No donations found.</td></tr> : filtered.map((row) => <tr key={row.id} className="border-t"><td className="p-3">{row.donationNo}</td><td className="p-3">{row.sponsor?.name || row.donorName || row.activity?.titleKm || "-"}</td><td className="p-3">{row.donationPeriod || new Date(row.paidAt).toLocaleDateString()}</td><td className="p-3">{Number(row.amountKhr || 0).toLocaleString()}</td><td className="p-3">{Number(row.amountUsd || 0).toLocaleString()}</td><td className="p-3">{row.paymentMethod?.labelKm || row.paymentMethod?.labelEn || row.paymentMethod?.code}</td><td className="p-3">{row.recordedBy?.fullNameKm || row.recordedBy?.fullNameEn || "-"}</td></tr>)}</tbody></table></div></div>;
}
