// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }

// app/layout.js
// app/layout.js
import { Kantumruy_Pro } from "next/font/google";
import { ThemeProvider } from "@/components/providers/themeProvider";
import "./globals.css";

const kantumruyPro = Kantumruy_Pro({
  subsets: ["khmer", "latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-kantumruy",
});

export const metadata = {
  title: "សមាគមយុវជនកម្ពុជា",
  description: "កម្មវិធីគ្រប់គ្រងសមាគមយុវជនកម្ពុជា",
};

export default function RootLayout({ children }) {
  return (
    <html lang="km" className={kantumruyPro.variable}>
      <body className={kantumruyPro.className}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}