import Image from "next/image";
import { gallery } from "./data";
export default function Gallery() {
  return (
    <section
      id="charity"
      className="
      scroll-mt-[82px]
      px-4
      py-10
      sm:px-6
      lg:px-10
      lg:py-12
      "
    >
      {/* Title */}
      <h2
        className="
        mt-10
        text-2xl
        font-extrabold
        text-[#17194d]
        sm:text-[32px]
        "
      >
        សកម្មភាពសប្បុរសធម៌របស់យើង
      </h2>
      <p
        className="
        mt-2
        text-sm
        text-gray-500
        "
      >
        រូបភាពខ្លះៗពីការចុះជួយសហគមន៍
      </p>
      {/* Images */}
      <div
        className="
        mt-8
        grid
        grid-cols-1
        gap-4
        sm:grid-cols-2
        lg:grid-cols-4
        lg:gap-5
        "
      >
        {gallery.map((item, index) => (
          <div
            key={index}
            className="
              group
              h-[220px]
              sm:h-[250px]
              overflow-hidden
              rounded-xl
              "
          >
            <Image
              src={item.image}
              width={400}
              height={200}
              alt={`gallery-${index}`}
              className="
                h-full
                w-full
                object-cover
                transition
                duration-300
                group-hover:scale-105
                "
            />
          </div>
        ))}
      </div>
    </section>
  );
}
