"use client";

import { useEffect, useMemo, useState } from "react";

export default function MyAccountParticipationPage() {
  const [rows, setRows] = useState([]); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { fetch("/api/backend/my-account/activities", { credentials: "include" }).then(async (r) => { const json=await r.json(); if(!r.ok) throw new Error(json?.message || "Unable to load activities."); setRows(json?.data ?? json ?? []); }).catch((reason) => setError(reason.message)).finally(() => setLoading(false)); }, []);
  const filtered=useMemo(() => { const q=query.toLowerCase().trim(); return rows.filter((r) => !q || [r.titleKm,r.titleEn,r.activityTypeLabelKm,r.activitySectorLabelKm,r.branchNameKm].some((v) => String(v||"").toLowerCase().includes(q))); }, [query,rows]);
  if(loading) return <div className="rounded-lg border bg-white p-6">Loading activities…</div>;
  return <div className="space-y-3">{error && <div className="rounded bg-red-50 p-3 text-red-700">{error}</div>}<input className="h-10 w-full max-w-sm rounded-lg border px-3" value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search activities"/><div className="overflow-x-auto rounded-lg border"><table className="w-full min-w-[750px] bg-white text-sm"><thead className="bg-gray-50 text-left"><tr><th className="p-3">Activity</th><th className="p-3">Type</th><th className="p-3">Sector</th><th className="p-3">Branch</th><th className="p-3">Start</th><th className="p-3">Attendance</th></tr></thead><tbody>{filtered.length===0?<tr><td colSpan="6" className="p-8 text-center">No activity participation found.</td></tr>:filtered.map((row)=><tr key={row.activityId} className="border-t"><td className="p-3 font-medium">{row.titleKm||row.titleEn}</td><td className="p-3">{row.activityTypeLabelKm||row.activityTypeLabelEn}</td><td className="p-3">{row.activitySectorLabelKm||row.activitySectorLabelEn}</td><td className="p-3">{row.branchNameKm||row.branchNameEn}</td><td className="p-3">{new Date(row.startsAt).toLocaleDateString()}</td><td className="p-3">{row.attendanceStatusLabelKm||row.attendanceStatusLabelEn||"Invited"}</td></tr>)}</tbody></table></div></div>;
}
